### PR TITLE
Add cookbook link

### PR DESCRIPTION
**Pull request by objarni**
I think the cookbook community effort deserves a mentioning on elm-ui frontpage

### CODE REVIEW

**Comment by mdgriffith** [comment]
I'm ok to add this, but I'd like to frame it as something the community wrote and maintains.

Mind changing the header to `Resources from the Community` or something similar?

**Comment by objarni** [comment]
Yeah, sure. What about "Community Cookbook"? And in the paragraph explain that it is maintained by some elm-ui enthusiast users? Like me :)

**Comment by objarni** [comment]
I updated the heading and paragraph, something like that?

**Comment by mdgriffith** [comment]
Wonderful, thank you!

**Pull request merged**
