### PR TITLE
Change signature of `modular` to return `Int` instead of `Float`

### LINKED ISSUE #36: Element.modular returns Float but Font.size requires Int
There is a discrepancy between the docs and the implementation for use of Element.modular. The example in the docs is

```elm
scaled =
    Scale.modular 16 1.25

Font.size (scaled 4) -- 16 * 1.25 ^ (4 - 1) results in 31.25
```

But this fails as Font.size expects an Int rather than a Float.

### PR DESCRIPTION
**Pull request by jcornaz**
So that it behaves as claimed by the documentation

Resolves #36

### CODE REVIEW

**Comment by andreacfromtheapp** [comment]
this is not the issue. the type annotation is correct.

see: https://github.com/mdgriffith/elm-ui/issues/36#issuecomment-1007703860 and https://github.com/mdgriffith/elm-ui/issues/331

**Comment by jcornaz** [comment]
I'm surprised by this statement.  But I don't use elm anymore, so I will not spend time trying to verify your claim.

And anyway, after almost two years without any message of the maintener in either the issue or this PR, I think it is time for me to close this.

**Comment by andreacfromtheapp** [comment]
> I'm surprised by this statement. But I don't use elm anymore, so I will not spend time trying to verify your claim.
> 
> And anyway, after almost two years without any message of the maintener in either the issue or this PR, I think it is time for me to close this.

that's understandable. thanks closing the issue on trust (or because you are pissed).

**Comment by jcornaz** [comment]
It's not really on trust. And I am not pissed either. It is just obvious by now, that the maintener is not interested in this issue, and it will not advance anytime soon.

But more importantly, even if it would gain sudden activity, I am no longer offering my contribution (either in form of code or discussion) because I moved on other things.

**Pull request closed without merging**
