### PR TITLE
Make classifyDevice's DeviceClass based on the shorter side of the window.

### PR DESCRIPTION
**Pull request by RosarioPulella**
This should help make the resulting DeviceClass more consistent.

### CODE REVIEW

**Comment by RosarioPulella** [comment]
Fixes #90

**Comment by mdgriffith** [comment]
Smart!

**Comment by RosarioPulella** [comment]
Thanks @mdgriffith, I'm glad I could contribute :smile: !

**Comment by mdgriffith** [comment]
Ok!  So I've been thinking about this because I want to release a new version.  Here's where I landed because this is subtle and you both made good points.

Basically I'm thinking that for phones we check short side.
For Tablets, we check short side & and long side.
For desktops we only check long side.

```elm
classifyDevice : { window | height : Int, width : Int } -> Device
classifyDevice window =
    { class =
        let
            longSide =
                max window.width window.height

            shortSide =
                min window.width window.height
        in
        
        if shortSide < 600 then
            Phone

        else if shortSide >= 600 && longSide <= 1200 then
            Tablet

        else if longSide > 1200 && longSide <= 1920 then
            Desktop

        else
            BigDesktop
    , orientation =
        if window.width < window.height then
            Portrait

        else
            Landscape
    }
```
It's weird because we're comparing multiple things now, but I think it works out.

The weird case is a tablet that has a short side above 600, and a long one above 1200.  In that case, it would be classified as a Desktop, which is fine with me.


Here's some reference device sizes that I looked at to check my logic: https://mediag.com/blog/popular-screen-resolutions-designing-for-all/

Which I turned into an ellie here:
https://ellie-app.com/68QtjR5cbbya1

Most everything checks out, even when we invert width/height.  The things that don't are tablets with high resolutions.

**Comment by mdgriffith** [comment]
Slight correction, we could probably drop the short side check on tablets.
So just
```
    else if longSide <= 1200 then
            Tablet
```

The other constraint is implied by the first case

**Pull request merged**
